Fixed nametag display inconsistency
diwako/diwako_dui pull request #190
Opened 2021-05-11 18:47 UTC by derbismarck

The `cursorObject` command will return an object representing the weapon a player is holding (or the launcher on their back) if you point at that when `cursorObject` is queried. This change piggybacks off of the new LIS check functionality in order to find what the `cursorObject` likely would have been, as there's no way to get from the weapon object to the unit who's holding it. See screenshots.

https://i.imgur.com/5MJPV4F.jpg
https://i.imgur.com/Uomn6Z3.jpeg

2021-05-11 21:00 UTC, diwako requested changes

2021-05-11 21:00 UTC, diwako commented on addons/nametags/functions/fnc_onDraw.sqf
> +// we'd like to find the cursorObject regardless, so we piggyback on the LIS check to find the most probable one
Move that into the if execution block of `GVAR(useLIS)` as it is only needed in there.

2021-05-14 12:34 UTC, diwako commented
Tested in local MP, it works there, shame it does not work in SP, but that is just a tidbit and can be ignored imo.

Will test in a larger op today or on Sunday and see if it works in a dedicated server environment.

2021-05-19 07:58 UTC, diwako approved these changes

2021-05-20 16:30 UTC, jokoho48 approved these changes

2021-05-20 23:12 UTC, merged